OBJECTIVE: 30

D	D	D	D	D	D	D	D	D	D	J	J	J	J	J	J	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	J	J	J	J	J	J	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	J	J	J	J	J	J	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	J	J	J	J	J	J	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	J	J	J	J	J	J	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	J	J	J	J	J	J	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	K	K	K	K	K	K	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	K	K	K	K	K	K	G	G	G	G	G	G	G	G	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	K	K	K	K	K	K	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
D	D	D	D	D	D	D	D	D	D	K	K	K	K	K	K	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
H	H	H	H	H	H	H	P	O	O	K	K	K	K	K	K	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
H	H	H	H	H	H	H		O	O	K	K	K	K	K	K	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
H	H	H	H	H	H	H	E	E	E	E	E	E	E	E	E	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
H	H	H	H	H	H	H	E	E	E	E	E	E	E	E	E	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
H	H	H	H	H	H	H	E	E	E	E	E	E	E	E	E	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
H	H	H	H	H	H	H	E	E	E	E	E	E	E	E	E	F	F	F	F	F	F	F	F	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	C	
H	H	H	H	H	H	H	E	E	E	E	E	E	E	E	E	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
I	I	I	I	I	I	I	E	E	E	E	E	E	E	E	E	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
I	I	I	I	I	I	I	E	E	E	E	E	E	E	E	E	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
I	I	I	I	I	I	I	E	E	E	E	E	E	E	E	E	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
I	I	I	I	I	I	I	E	E	E	E	E	E	E	E	E	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
I	I	I	I	I	I	I	N	N	N	M	M	M	L	L	L	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
I	I	I	I	I	I	I	N	N	N	M	M	M	L	L	L	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
I	I	I	I	I	I	I	N	N	N	M	M	M	L	L	L	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	B	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	A	
